language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install xmltodict
script:
  python new-books.py
deploy:
  provider: pages
  local_dir: gh-pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
notifications:
  email:
    recipients:
      - aschriver@artic.edu
    on_success: never # default: change
    on_failure: always # default: always
