name: newbooks

on:
  schedule:
    - cron: "30 22 * * *" # runs at 22:30 UTC (5:30 PM CDT) everyday

  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: checkout repo content
          uses: actions/checkout@v2

        - name: setup python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8

        - name: execute py script
          run: |
            cd docs
            python new-books.py

        - name: deploy to github pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./docs
            force_orphan: true
